/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:controls_window:409447:
  appc.background(#161C46);
} //_CODE_:controls_window:409447:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:509619:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:509619:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:607161:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:607161:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:918390:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:918390:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  controls_window = GWindow.getWindow(this, " Controls - VectorDraw", 0, 0, 250, 800, JAVA2D);
  controls_window.noLoop();
  controls_window.setActionOnClose(G4P.KEEP_OPEN);
  controls_window.addDrawHandler(this, "win_draw1");
  button1 = new GButton(controls_window, 10, 70, 230, 30);
  button1.setText("Face text");
  button1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(controls_window, 10, 110, 230, 30);
  button2.setText("Face text");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(controls_window, 10, 150, 230, 30);
  button3.setText("Face text");
  button3.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  label1 = new GLabel(controls_window, 10, 30, 230, 30);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("My label");
  label1.setOpaque(false);
  controls_window.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controls_window;
GButton button1; 
GButton button2; 
GButton button3; 
GLabel label1; 
